### ISSUE TITLE
Stop this and work on schematell

### ISSUE THREAD

**Issue by blaumeise20** [Just-a-Unity-Dev/atomdustry#1]
.

**Comment by Just-a-Unity-Dev** [comment]
can you stop fucking asking me to WORK ON SCHEMATELL??? FOR LIKE 5 MINUTES??? I WANNA MAKE A SIDE PROJECT AND THEN YOU HAVE TO FUCKING TELL ME TO GET TO WORK. I DONT GET FUCKING PAID FOR THIS SHIT. I DONT FUCKING RECEIVE MONEY. I RECEIVE DONATIONS (WHICH, BY THE WAY HAS ONLY BEEN 0$ WORTH IN REVENUE). YOU TOO DONT DONATE TO ME, IM DOING SCHEMATELL OUT OF FUCKING BOREDOM. AND IM TIRED OF SCHEMATELL. STOP GETTING IN THE WAY OF MY PROJECTS THAT I LIKE WITH MOTHERFUCKING SCHEMATELL

tl;dr: GO FUCK YOURSELF

**Comment by Just-a-Unity-Dev** [comment]
locked due to more idiots complaining about an old game, ill pin this too
